title: Cheatsheets
description: TO BE UPDATED
theme: just-the-docs

url: https://shiivanks.github.io/cheatsheets

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/shiivanks/cheatsheets